### ISSUE TITLE
not work with Android 13 in Miui14.0.4.0 

### ISSUE THREAD

**Issue by zerorooot** [Palatis/XAppDebug#4]
XAppDebug version 1.0.5 , download in 
https://github.com/Xposed-Modules-Repo/tw.idv.palatis.xappdebug/releases

```txt
java.lang.NoSuchMethodError: com.android.server.pm.PackageManagerService#getPackageInfo(java.lang.String,int,int)#exact
	at de.robv.android.xposed.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.h(Unknown Source:0)
	at de.robv.android.xposed.d.get(Unknown Source:13)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:25)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:4)
	at tw.idv.palatis.xappdebug.xposed.HookMain.handleLoadPackage(Unknown Source:41)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at p.beforeHookedMethod(Unknown Source:164)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.startBootstrapServices(Unknown Source:11)
	at com.android.server.SystemServer.run(SystemServer.java:998)
	at com.android.server.SystemServer.main(SystemServer.java:704)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
```
It looks like "getPackageInfo" changed in android 13，Can you fix it？

Some message :
https://stackoverflow.com/questions/73388061/android-13-sdk-33-packagemanager-getpackageinfostring-int-deprecated-what

**Comment by zerorooot** [comment]
Hi, I researched the relevant source code of android 13 and found that it changed the relevant class in "PackageManagerService" to "ComputerEngine". "getInstalledApplicationsListInternal" was renamed to "getInstalledApplications", and the type of "flags" became "long"

If you have time, you can update the code, Thanks♪(･ω･)ﾉ

ComputerEngine.java  source code:
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/pm/ComputerEngine.java

git diff
https://github.com/Palatis/XAppDebug/commit/25a42c059730e67627db927c7a944eb99f0e1835#diff-00d9a00e075f36075c814dc0d53578dd355fbf2a836db592fd7eac075415bfe2

**Comment by Palatis** [comment]
I currently don't have time on this project for the moment (and I don't own any Android 13 device, either), but I do accept PRs.

**Comment by ElJaviLuki** [comment]
Fixed in #5 pull request :)
Asking permission for closing this issue!
